/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#aec7f6",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-container-high": "#eae7e7",
        "secondary-container": "#fed488",
        "on-surface-variant": "#44474e",
        "on-surface": "#1c1b1b",
        "primary-container": "#002147",
        "on-secondary-fixed-variant": "#5d4201",
        background: "#fcf9f8",
        "on-primary-fixed-variant": "#2d476f",
        "on-primary": "#ffffff",
        tertiary: "#090b0c",
        secondary: "#775a19",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        primary: "#000a1e",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed": "#001b3d",
        "surface-bright": "#fcf9f8",
        "surface-tint": "#465f88",
        "tertiary-container": "#1f2223",
        "on-error": "#ffffff",
        "surface-dim": "#dcd9d9",
        surface: "#fcf9f8",
        "inverse-surface": "#313030",
        "on-secondary": "#ffffff",
        "on-background": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "on-primary-container": "#708ab5",
        "on-tertiary-fixed-variant": "#454748",
        "surface-container": "#f0eded",
        outline: "#74777f",
        "surface-variant": "#e5e2e1",
        "secondary-fixed-dim": "#e9c176",
        "on-tertiary-container": "#87898a",
        "secondary-fixed": "#ffdea5",
        "on-tertiary-fixed": "#191c1d",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#aec7f6",
        "outline-variant": "#c4c6cf",
        "on-secondary-fixed": "#261900",
        "tertiary-fixed": "#e1e3e4",
        "on-secondary-container": "#785a1a",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        base: "8px",
        "margin-desktop": "64px",
        xs: "4px",
        md: "24px",
        "margin-mobile": "16px",
        xl: "80px",
        lg: "48px",
        gutter: "24px",
      },
      fontFamily: {
        "arabic-headline": ["Noto Naskh Arabic"],
        "body-lg": ["Noto Sans"],
        "arabic-body": ["Noto Naskh Arabic"],
        "display-lg-mobile": ["Noto Sans"],
        "headline-md": ["Noto Sans"],
        "display-lg": ["Noto Sans"],
        "label-sm": ["Noto Sans"],
        "body-md": ["Noto Sans"],
      },
      fontSize: {
        "arabic-headline": ["26px", { lineHeight: "44px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "arabic-body": ["18px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
