# Generated by Django 5.2.15 on 2026-06-10 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=100)),
                ('session_date', models.DateField()),
                ('academic_year', models.CharField(max_length=20)),
                ('study_year', models.IntegerField()),
                ('branch', models.CharField(max_length=150)),
                ('ecrit_subject_1', models.CharField(blank=True, max_length=200, null=True)),
                ('ecrit_subject_2', models.CharField(blank=True, max_length=200, null=True)),
                ('ecrit_subject_3', models.CharField(blank=True, max_length=200, null=True)),
                ('ecrit_subject_4', models.CharField(blank=True, max_length=200, null=True)),
                ('oral_subject_1', models.CharField(blank=True, max_length=200, null=True)),
                ('oral_subject_2', models.CharField(blank=True, max_length=200, null=True)),
                ('oral_subject_3', models.CharField(blank=True, max_length=200, null=True)),
                ('oral_subject_4', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('exam_number', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=150)),
                ('academic_year', models.CharField(max_length=20)),
                ('study_year', models.IntegerField()),
                ('branch', models.CharField(max_length=150)),
                ('print_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('professor', 'Professeur')], default='professor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('entity', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('print_number', models.IntegerField()),
                ('is_admin_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='releves.student')),
            ],
            options={
                'db_table': 'print_logs',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ecrit_score_1', models.FloatField(blank=True, null=True)),
                ('ecrit_score_2', models.FloatField(blank=True, null=True)),
                ('ecrit_score_3', models.FloatField(blank=True, null=True)),
                ('ecrit_score_4', models.FloatField(blank=True, null=True)),
                ('written_total', models.FloatField(blank=True, null=True)),
                ('written_result', models.CharField(blank=True, max_length=20)),
                ('oral_score_1', models.FloatField(blank=True, null=True)),
                ('oral_score_2', models.FloatField(blank=True, null=True)),
                ('oral_score_3', models.FloatField(blank=True, null=True)),
                ('oral_score_4', models.FloatField(blank=True, null=True)),
                ('oral_total', models.FloatField(blank=True, null=True)),
                ('general_total', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('general_result', models.CharField(blank=True, max_length=20)),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='releves.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='releves.student')),
            ],
            options={
                'db_table': 'grades',
                'unique_together': {('student', 'session')},
            },
        ),
    ]
