"""initial_schema

Revision ID: 6430256ccd45
Revises: 
Create Date: 2026-06-03 13:36:00.525873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6430256ccd45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('exam_number', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_place', sa.String(length=150), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('study_year', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=True),
    sa.Column('total_written', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_oral', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_general', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('average', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('general_result', sa.String(length=20), nullable=True),
    sa.Column('mention', sa.String(length=50), nullable=True),
    sa.Column('copy_general', sa.String(length=50), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_birth_date'), 'students', ['birth_date'], unique=False)
    op.create_index(op.f('ix_students_exam_number'), 'students', ['exam_number'], unique=False)
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'professor', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('note', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('written_result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('printed_by', sa.String(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=False),
    sa.Column('print_number', sa.Integer(), nullable=False),
    sa.Column('is_admin_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['printed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_logs')
    op.drop_table('grades')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.drop_index(op.f('ix_students_exam_number'), table_name='students')
    op.drop_index(op.f('ix_students_birth_date'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
